create table if not exists order_info (
    id bigint primary key auto_increment comment '订单ID',
    order_no varchar(64) not null unique comment '订单编号',
    appointment_id bigint null comment '预约ID',
    customer_id bigint not null comment '客户ID',
    service_item_id bigint not null comment '服务项目ID',
    card_type varchar(20) not null default '次卡' comment '卡类型：当前只记录次卡',
    original_amount decimal(10, 2) not null default 0.00 comment '原价/卡费',
    discount_amount decimal(10, 2) not null default 0.00 comment '优惠金额',
    amount decimal(10, 2) not null default 0.00 comment '应收金额',
    paid_amount decimal(10, 2) not null default 0.00 comment '已收金额',
    debt_amount decimal(10, 2) not null default 0.00 comment '欠款金额',
    monthly_payment decimal(10, 2) not null default 0.00 comment '每月计划还款',
    payment_method varchar(20) not null default '现金' comment '支付方式：微信、支付宝、现金、次卡',
    debt_status tinyint not null default 0 comment '欠款状态：0无欠款，1分期中，2已结清',
    pay_status tinyint not null default 0 comment '支付状态：0未支付，1已支付，2已退款',
    order_status tinyint not null default 0 comment '订单状态：0待服务，1已完成，2已取消',
    pay_time datetime null comment '支付时间',
    remark varchar(255) null comment '备注',
    create_time datetime not null comment '创建时间',
    update_time datetime not null comment '更新时间',
    index idx_order_info_customer_id (customer_id),
    index idx_order_info_service_item_id (service_item_id),
    index idx_order_info_appointment_id (appointment_id),
    index idx_order_info_create_time (create_time),
    index idx_order_info_payment_method (payment_method),
    index idx_order_info_debt_status (debt_status),
    index idx_order_info_pay_status (pay_status),
    index idx_order_info_order_status (order_status)
) comment '订单表';
